### ISSUE TITLE
Waggster bltouch?

### ISSUE THREAD

**Issue by Chazy12** [Guilouz/Marlin-Sidewinder-X1-SKR1.4-Turbo#1]
Hello.
I would ask if the firmware is wired for bltouch classic or wired for waggster.
Couse i have a waggster wired bltouch.
And i would ask if it's possible to compile it with TMC 2208 UART too.
Thanks a lot.

**Comment by Guilouz** [comment]
Configuration is set to use dedicated SERVOS and PROBE ports on motherboard. So you can use waggster or not, it doesn't matter as long as the bltouch is plugged into the correct ports.

And yes you can use TMC2208, just change them in Configuration.h.
