### ISSUE TITLE
auto-level sensor 

### ISSUE THREAD

**Issue by sasha892046** [Guilouz/Marlin-Sidewinder-X1-SKR1.4-Turbo#2]
hello, tell me please, I flashed the skr 1.4 turbo board with an auto-level sensor with your firmware and when leaving home, the x and z axes go home and go to the measurement positions in the center of the table and the z axis rises by 10 mm and extends the probe several times but the z axis does not move after  why does the printer give an error

**Comment by Guilouz** [comment]
What kind of sensor ?

**Comment by sasha892046** [comment]
BLTouch clone

**Comment by Guilouz** [comment]
Depend of clone you use, my configuration is for official BLTouch.
