### ISSUE TITLE
Question SKR 1.4 + TMC 2209 - UART - Sensorless

### ISSUE THREAD

**Issue by SckyzO** [Guilouz/Marlin-Sidewinder-X1-SKR1.4-Turbo#3]
Hello @Guilouz 
Je me posais la question, avec ton FM est ce que le Sensorless est actif ? 
Ou alors avec une SKR1.4 Turbo + TMC2209 il faut couper la pin du Diag ? 

Merci

**Comment by Guilouz** [comment]
Non il n'est pas actif. Oui il faut les couper si pas utilisé.
